### ISSUE TITLE
Missing credential in multi_pool.md 

### ISSUE THREAD

**Issue by mmalvezz** [gotsysdba/oracle-ords-operator#37]
I'm testing oracle-ords-operator/docs/examples/multi_pool.md
The init_ords.sh scripts fails with the following error on pdb1 

```
Found Pool: pdb1...
db.password in pool pdb1, not defined
db.adminUser.password in pool pdb1, not defined
db.cdb.adminUser.password in pool pdb1, not defined
FATAL: db.password must be specified for pdb1
Pool: pdb1, Exit Code: 1

```
it seems that some credential is missing in the multi_pool.md example 

```
echo "
apiVersion: database.oracle.com/v1
kind: RestDataServices
metadata:
  name: ords-multi-pool
spec:
  image: container-registry.oracle.com/database/ords:23.4.0
  forceRestart: true
  globalSettings:
    database.api.enabled: true
  poolSettings:
    - poolName: pdb1
      autoUpgradeORDS: true
      autoUpgradeAPEX: true
      db.connectionType: tns
      db.tnsAliasName: DB1
      tnsAdminSecret:
        secretName: multi-tns-admin
      restEnabledSql.active: true
      feature.sdw: true
      plsql.gateway.mode: proxied
      db.username: ORDS_PUBLIC_USER
      db.secret:
        secretName: pdb1-ords-auth
      db.adminUser: SYS
      db.adminUser.secret:
        secretName: pdb1-priv-auth" | kubectl apply -f -
```
